[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[redirects]]
from = "/api/ask"
to = "/.netlify/functions/ask"
status = 200
force = true

[[redirects]]
from = "/api/ingest"
to = "/.netlify/functions/ingest"
status = 200
force = true

[[redirects]]
from = "/api/images"
to = "/.netlify/functions/images"
status = 200
force = true
